### ISSUE TITLE
Is there something wrong in the theme provider?

### ISSUE THREAD

**Issue by LoniasGR** [LoniasGR/mystery-chat#9]
I am trying to wrap my head around the theme provider [here](https://github.com/LoniasGR/mystery-chat/blob/main/mystery-frontend/src/components/theme-provider.tsx). 

I feel that the theme could never have the value of `system,` which is kind of odd. Also, I think I need to change what we did in #3, to match the attribute of theme-color with the actual theme being used, cause now they are out of sync.

**Comment by pawicao** [comment]
Yeah so the shadcn component by default came with the defaultOption prop in the ThemeProvider set to system

I think I changed it to dark there, and in that case yeah, we can never get the system option (I did that to kinda match the look and feel of all darker materials we were sending to guests so far)

I would be okay with changing the default to system if you think it's better

And I agree with your second sentence, it would be good to keep that theme-color in sync

**Comment by LoniasGR** [comment]
Okay, I will work a bit on this.
